### ISSUE TITLE
Plugin 'Mongo DB Browser' (version '2022.3.2') is not compatible with the current version of the PyCharm 2023.1

### ISSUE THREAD

**Issue by squeezer44** [geetesh-gupta/Mongo-DB-Browser#10]
Hi :-),

after starting my PyCharm IDE 

PyCharm 2023.1 (Professional Edition)
Build #PY-231.8109.197, built on March 29, 2023
Runtime version: 17.0.6+10-b829.5 amd64

I'm getting this Plugin error:

_**Plugin 'Mongo DB Browser' (version '2022.3.2') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is PY-231.8109.197**_

Any suggestions to fix this?

Thx in advance

**Comment by geetesh-gupta** [comment]
Need to update the plugin supported versions. Will update and inform here as soon as possible.

**Comment by squeezer44** [comment]
@geetesh-gupta 
thx in advance - I love it to use the Mongo DB Browser.

**Comment by geetesh-gupta** [comment]
Hi @squeezer44 
The version has been updated to support latest versions of IDEs. Please try to install the new version 2023.1.1

**Comment by squeezer44** [comment]
Hi @geetesh-gupta ,
checked after update to the latest version of Mongo DB Browser 2023.1.1: confirmed, it works as hoped.

Thx a lot!
