### ISSUE TITLE
Not compatible with the version of your running IDE (PyCharm 2023.2)

### ISSUE THREAD

**Issue by squeezer44** [geetesh-gupta/Mongo-DB-Browser#11]
Due to this error message

_Not compatible with the version of your running IDE (PyCharm 2023.2)_

I needed to deinstall my lovely Mongo DB Browser 2023.1.1.

Are there any plannings to make it compatible with PyCharm 2023.2?

**Comment by neurobe** [comment]
me 2

**Comment by squeezer44** [comment]
Any new issues regarding this issue?
Currently the Mongo-DB-Browser isn*t compatible with the newest Pycharm Release - this is very sad.

Thx for an update.

**Comment by geetesh-gupta** [comment]
Oh, missed the issue notification 😔. Will update and fix.

**Comment by geetesh-gupta** [comment]
@squeezer44 @neurobe please check with the latest version now.

**Comment by squeezer44** [comment]
@geetesh-gupta : Thx - for me it's working again with Mongo DB Browser 2023.2.1
