### ISSUE TITLE
Plugin MongoDB Browser is not compatible with the vurrent version of the IDE

### ISSUE THREAD

**Issue by squeezer44** [geetesh-gupta/Mongo-DB-Browser#12]
Ahoi,

I jeust updated my PyCharm IDE to 2023.3 and received this message after IDE has started:

_Plugin 'Mongo DB Browser' (version '2023.2.1') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is PY-233.11799.259_

I would like to keep using the Mongo DB Browser - so can you please fix this?

Thx a lot

**Comment by geetesh-gupta** [comment]
Hi @squeezer44 I will try to update the version as soon as possible

**Comment by geetesh-gupta** [comment]
@squeezer44 Plugin has been updated to support latest IDE versions. Kindly upgrade to the latest version.

**Comment by squeezer44** [comment]
@geetesh-gupta Thx a lot.
Mongo DB Borwser 2023.3.1 installed within PyCharm 2023.3.1 (Build #PY-233.11799.2989:
IDE Restart is running without any errors and the Plugin is working again.

Thx a lot :-)

I wish you a happy new year.
