### ISSUE TITLE
The interface "dies" when trying to connect to a disabled database

### ISSUE THREAD

**Issue by JUSSIAR** [geetesh-gupta/Mongo-DB-Browser#13]
We raise mongo in the docker, join, and everything works. I stop the container, try to refresh the database from the DataGrid management, and instead of some error, the datagrip freezes for half a minute or a minute, spending about 30 percent of the CPU load (M1 pro, 32 RAM).

**Comment by geetesh-gupta** [comment]
Hi @JUSSIAR Thanks for identifying and sharing the issue. I have fixed the issue. It will be available soon in the marketplace. Will update here once the latest version is available.

**Comment by geetesh-gupta** [comment]
Fix is available in the latest version 2024.2.3.
