### ISSUE TITLE
Incompatible: requires IDE build 233.* or earlier

### ISSUE THREAD

**Issue by uwainium** [geetesh-gupta/Mongo-DB-Browser#14]
![image](https://github.com/geetesh-gupta/Mongo-DB-Browser/assets/16182738/a9fdd623-1326-43c0-b81b-35ec4b6a745d)

**Comment by Waysti** [comment]
Same here, could you please update the plugin?

**Comment by geetesh-gupta** [comment]
Sure, will update and inform.

**Comment by geetesh-gupta** [comment]
Updated... please upgrade to the latest version... thanks for using the plugin.
