### ISSUE TITLE
Incompatible: requires IDE build 233.* or earlier - but I'm using 242.*

### ISSUE THREAD

**Issue by squeezer44** [geetesh-gupta/Mongo-DB-Browser#18]
Hi,

sadly, the MongoDB Browser is getting inactivated, because I just updated my PyCharm IDE:
![grafik](https://github.com/user-attachments/assets/3525ef3c-4898-4647-b43a-396f8eaff0cd)

- My current version:
PyCharm 2024.2.2 (Professional Edition)
Build #PY-242.22855.92, built on September 19, 2024

Could you please adapt the version compatibility?

**Comment by geetesh-gupta** [comment]
Will update

**Comment by geetesh-gupta** [comment]
Update available now. Please validate. Thanks

**Comment by squeezer44** [comment]
Validation completed: it works :-)

Thx
