### ISSUE TITLE
Version 0.1.2 not compatible with WebStorm 2022.3

### ISSUE THREAD

**Issue by HelgeStenstrom** [geetesh-gupta/Mongo-DB-Browser#7]
According to the WebStorm plugin settings, Mongo DB Browser requires IDE build 222.* or earlier. WebStorm 2022.3 is IDE build #WS-223.7571.168 (on Windows).
<img width="270" alt="Screenshot 2022-12-12 09 30 33" src="https://user-images.githubusercontent.com/169443/206998853-65415d38-29d3-4de6-93c7-1bc185352a00.png">
<img width="332" alt="Screenshot 2022-12-12 09 32 25" src="https://user-images.githubusercontent.com/169443/206998871-f47fbb88-1f62-4001-9f56-32c682f3e986.png">

**Comment by geetesh-gupta** [comment]
It should work but will check.  I think JetBrains has again updated API for IDE versions going forward.

**Comment by geetesh-gupta** [comment]
Hi @HelgeStenstrom 222.* means versions including 2022.2.*. You can check the https://plugins.jetbrains.com/plugin/20002-mongo-db-browser/versions for more details regarding the support.

**Comment by geetesh-gupta** [comment]
Added compatibility for latest IDE versions 223.* in new plugin version 2022.3.2
