### ISSUE TITLE
Add support for mongo+srv url

### ISSUE THREAD

**Issue by PierrickPuimeanChieze** [geetesh-gupta/Mongo-DB-Browser#8]
Currently, you cannot connect to MongoDb Atlas, because they provide only URL using the +srv schema. Could be useful to allow for use of this schema

**Comment by geetesh-gupta** [comment]
Okay will have a look.

**Comment by dorbareket** [comment]
Also, it would be awesome if it was possible to copy a DB link from 3T studio and paste it in IntelliJ

**Comment by geetesh-gupta** [comment]
I would be more than happy to take a look as soon as I am able.

**Comment by evilive3000** [comment]
A vitally important feature, I'm looking forward to it.

**Comment by geetesh-gupta** [comment]
The support for mongo+srv url is available now. Kindly upgrade to the latest version 2024.2.1

**Comment by anshulahuja98** [comment]
@evilive3000 @PierrickPuimeanChieze  where you able to try out the latest version and validate if it works for you?

**Comment by evilive3000** [comment]
Thank you so much for this feature. Can't get into reconfiguring a running system at the moment. But I will be setting up a new dashboard in the near future, and I will definitely use this functionality.
